CREATE DATABASE INTERSHIPTASK
USE INTERSHIPTASK


CREATE TABLE Departments (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(50),
    location VARCHAR(50),
    budget MONEY
);

CREATE TABLE Employees (
    emp_id INT PRIMARY KEY,
    name VARCHAR(50),
    department_id INT,
    salary MONEY,
    hire_date DATE,
    FOREIGN KEY (department_id) REFERENCES Departments(department_id)
);

INSERT INTO Departments VALUES
(1, 'HR', 'New York', 50000),
(2, 'IT', 'Chicago', 120000),
(3, 'Finance', 'New York', 90000),
(4, 'Marketing', 'Boston', 70000);

INSERT INTO Employees VALUES
(101, 'Alice', 1, 40000, '2020-05-10'),
(102, 'Bob', 2, 80000, '2019-03-15'),
(103, 'Charlie', 2, 60000, '2021-07-22'),
(104, 'David', 3, 75000, '2020-11-01'),
(105, 'Emma', 4, 65000, '2022-01-18'),
(106, 'Frank', 1, 45000, '2021-09-30'),
(107, 'Grace', 3, 90000, '2018-12-05'),
(108, 'Henry', 2, 95000, '2022-03-10');


--SCALAR SUBQUERY EXAMPLE
--FIND THE EMPLOYEE WITH HIGEST SALARY

SELECT * FROM Employees WHERE 
SALARY =(SELECT MAX(SALARY) FROM Employees) 

--LIST ALL EMPLOYEES WHO WERE HIRED ON THE SAME DATE AS THE EARLIST HIRED EMPLOYEE

SELECT * FROM EMPLOYEES WHERE
HIRE_DATE=(SELECT MIN(HIRE_DATE) FROM Employees)

-- SHOW THE DEPARTMENT WHOSE BUDGET IS EQUL TO THE AVERAGE BUDGET OF ALL DEPARTMENTS

SELECT * FROM Departments
SELECT * FROM Employees

SELECT department_name FROM Departments
WHERE BUDGET =(SELECT SUM(BUDGET) FROM Departments)

--LIST EMPLOYEES WHOSE SALARY IS ABOVE THE AVERAGE SALARY OF THEIRE DEPARTMENT

SELECT * FROM Employees
WHERE SALARY>(SELECT AVG(BUDGET)  FROM Departments)

--FIND THE EMP WHOWORKS IN NEW YORK DEPARTMENT

SELECT *
FROM  Employees WHERE department_id IN( SELECT department_id FROM Departments WHERE location='NEW YORK')

--SUB QUERY WITH EXISTS
--LIST DEPARTMENTS THAT HAVE AT LEAST ONE EMP EARNING MORE THAN 80000

SELECT DEPARTMENT_NAME FROM Departments D WHERE  EXISTS(SELECT * FROM Employees E WHERE E.department_id=D.department_id 
AND E.salary>=80000)

--FIND EMP WORKING IN THE DEPARTMENT WITH THE HIGEST BUDGET

SELECT * FROM Departments
SELECT * FROM Employees

SELECT * FROM Employees WHERE department_id=(SELECT TOP 1 department_id FROM Departments
ORDER BY BUDGET DESC  )